// config.h
// This file is generated by cmake from config.h.in
// Things that may change based on the build directory, such as paths to files
// and the file version are procedurally generated by cmake here

// Define component version
#define TEMPLATE_VERSION_MAJOR 1
#define TEMPLATE_VERSION_MINOR 0
#define TEMPLATE_VERSION_PATCH 0

// Define resource folder for UT suite
// This path points to the folder with sample .cfg files
#define TEMPLATE_UT_RESRC_PATH "/home/brxwoodruff/cpptemplate/test/cfg"
